"""add due_at to todos

Revision ID: 0286498ce498
Revises: 169ce24a545d
Create Date: 2026-07-20 14:45:59.244828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0286498ce498'
down_revision: Union[str, Sequence[str], None] = '169ce24a545d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_todos_due_at'), 'todos', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_due_at'), table_name='todos')
    op.drop_column('todos', 'due_at')
    # ### end Alembic commands ###
